# Generated by Django 4.2.6 on 2024-02-16 17:23

from django.db import migrations

def create_categories(apps, schema_editor):
    Category = apps.get_model('api', 'Category')
    categories = ['General', 'Relationship', 'Beauty', 'Career', 'Education', 'Finance']
    for category_name in categories:
        Category.objects.create(name=category_name)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_category_remove_profile_dob_and_more'),
    ]

    operations = [
        migrations.RunPython(create_categories),
    ]
