# Generated by Django 4.2.6 on 2024-02-17 00:19

# Generated by Django 4.2.6 on 2024-02-17 00:15

# Generated by Django 4.2.6 on 2024-02-16 17:23

from django.db import migrations

def create_categories(apps, schema_editor):
    Category = apps.get_model('api', 'Category')
    categories = [
        {'name': 'General', 'icon': 'categories/general.png'},
        {'name': 'Relationship', 'icon': 'categories/relationship.png'},
        {'name': 'Beauty', 'icon': 'categories/beauty.png'},
        {'name': 'Career', 'icon': 'categories/career.png'},
        {'name': 'Education', 'icon': 'categories/education.png'},
        {'name': 'Finance', 'icon': 'categories/finance.png'},
    ]
    for category_data in categories:
        Category.objects.create(name=category_data['name'], icon=category_data['icon'])

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20240217_0015'),
    ]

    operations = [
        migrations.RunPython(create_categories),
    ]